//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shanu_QuizWcfService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Character_Type
    {
        public Character_Type()
        {
            this.Character_Name = new HashSet<Character_Name>();
        }
    
        public string Char_ID { get; set; }
        public string Profes_ID { get; set; }
        public string Char_Type { get; set; }
    
        public virtual ICollection<Character_Name> Character_Name { get; set; }
        public virtual Professional_Type Professional_Type { get; set; }
    }
}
