//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shanu_QuizWcfService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Character_Name
    {
        public Character_Name()
        {
            this.Questions = new HashSet<Questions>();
        }
    
        public string Char_Name_ID { get; set; }
        public string Char_ID { get; set; }
        public string Char_Name { get; set; }
        public string Char_Status { get; set; }
    
        public virtual ICollection<Questions> Questions { get; set; }
        public virtual Character_Type Character_Type { get; set; }
    }
}
