//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shanu_QuizWcfService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Professional_Type
    {
        public Professional_Type()
        {
            this.Character_Type = new HashSet<Character_Type>();
        }
    
        public string Profes_ID { get; set; }
        public string Profes_Type { get; set; }
    
        public virtual ICollection<Character_Type> Character_Type { get; set; }
    }
}
