//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shanu_QuizWcfService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questions
    {
        public string Question_ID { get; set; }
        public string Char_Name_ID { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
    
        public virtual Character_Name Character_Name { get; set; }
    }
}
