//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shanu_QuizWcfService.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class shanuQuizEntities : DbContext
    {
        public shanuQuizEntities()
            : base("name=jQuizEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Character_Name> Character_Name { get; set; }
        public DbSet<Character_Type> Character_Type { get; set; }
        public DbSet<Professional_Type> Professional_Type { get; set; }
        public DbSet<Questions> Questions { get; set; }
    }
}
